version: '2'
services:

    web:
        build: ./
        volumes:
            - ./:/var/www/html/
            - ~/.composer/cache:/root/.composer/cache
            - ~/.ssh:/root/.ssh
            - ./services/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - mysql
            - redis
        environment:
            ENABLE_ENV_FILE: 1
            ENABLE_LOCALCONF: 1
            API_TOKEN: "47591fb1175145933b20f80d89c9da0381e9339a"
        expose:
            - 9000

    nginx:
        image: zacksleo/nginx:yii2
        ports:
            - "80:80"
        links:
            - web
        volumes_from:
            - web

    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: web
        volumes:
            - ./deploy/development/mysql:/var/lib/mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    redis:
        image: redis:latest
        expose:
            - "6379"