version: '2'
services:

    web:
        build: ./
        volumes:
            - ./:/var/www/html/
            - ~/.composer/cache:/root/.composer/cache
            - ~/.ssh:/root/.ssh
        links:
            - mysql
            - redis
        expose:
            - 9000

    nginx:
        image: zacksleo/nginx:yii2
        ports:
            - "80:80"
        links:
            - web
        volumes_from:
            - web

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_USER}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./deploy/development/mysql:/var/lib/mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    redis:
        image: redis:latest
        expose:
            - "6379"