version: '2'
services:

    web:
        container_name: ${APP_ID}
        image: registry.domain.com/namespace/${APP_ID}:${TAG}
        volumes:
            - ./.env:/var/www/html/.env
            - ./data/api/runtime:/var/www/html/api/runtime
            - ./data/api/web/assets:/var/www/html/api/web/assets
            - ./data/backend/runtime:/var/www/html/backend/runtime
            - ./data/backend/rbac:/var/www/html/backend/rbac
            - ./data/backend/web/assets:/var/www/html/backend/web/assets
            - ./data/console/runtime:/var/www/html/console/runtime
            - ./data/frontend/runtime:/var/www/html/frontend/runtime
            - ./data/frontend/web/assets:/var/www/html/frontend/web/assets
            - ./data/frontend/web/uploads:/var/www/html/frontend/web/uploads
        expose:
            - 9000
        restart: always

    nginx:
        image: zacksleo/nginx:yii2
        ports:
            - "80:80"
        links:
            - web
        volumes_from:
            - web
        restart: always

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${APP_ID}
            MYSQL_USER: ${APP_ID}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./deploy/development/mysql:/var/lib/mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

    redis:
        image: redis:alpine
        expose:
            - "6379"


